import DisplayTypesExample from "../components/DisplayTypesExample/DisplayTypesExample";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import Head from "next/head";
import Link from "next/link";
import Navbar from "../components/Navbar/Navbar";
import { faEye } from "@fortawesome/free-solid-svg-icons";
import styles from "./index.module.scss";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className={styles.hero}>
        <div className={styles.col}>
          <h1>
            Display <span className="highlight">your</span> photos the way{" "}
            <span className="highlight">you</span> want.
          </h1>
          <Link href="/" className="btn">
            <a className="btn">Create your own</a>
          </Link>
          <Link href="/" className="sub-btn">
            <a className="btn-g">
              <FontAwesomeIcon icon={faEye} />
              Preview
            </a>
          </Link>
        </div>
        <div className={styles.col}>
          <DisplayTypesExample />
        </div>
      </div>
    </div>
  );
}
